### ISSUE TITLE
Color not recognized from SVG

### ISSUE THREAD

**Issue by dakoller** [t-oster/VisiCut#408] opened 2017-04-12 20:09 UTC
Hi all,

from the attached SVG file no colors are recognized, the only selection criteria, which  show up as colors are
- black,
- everything and
- everything, which has another color.

Could you please take a look?

[ma_big3b.svg.zip](https://github.com/t-oster/VisiCut/files/917733/ma_big3b.svg.zip)

Kind regards,

Daniel

**Comment by pelrun** [comment] 2017-04-14 05:17
I think this is the same as #339 - Visicut only recognises inline styles, not those defined in CSS blocks.

Separately (but probably not a contributing factor), the SVG is corrupted and truncated.

**Comment by jnweiger** [comment] 2017-12-25 22:55
Yes, it looks very much like a duplicate of #339

**Closed** 2017-12-26 13:26 UTC
