### ISSUE TITLE
Struggling to launch version 1.8-103 on Win11

### ISSUE THREAD

**Issue by calamityj** [t-oster/VisiCut#624] opened 2021-10-28 20:51 UTC
I just see this error on startup:

![image](https://user-images.githubusercontent.com/61735863/139333788-dce1a38c-35fd-4707-a9d7-f950f28a28ed.png)

**Comment by mgmax** [comment] 2021-11-09 17:47
https://github.com/t-oster/VisiCut/wiki/Development:-Running-from-commandline

**Comment by sebastian-schmid** [comment] 2021-11-30 15:18
I tested this today on a clean Win11 Home (VM) Installation with Inkscape 1.1 and VisiCut 1.9-113-g02234deb and it worked out of the box.

@calamityj please try again with latest VisiCut 1.9 and if you still get the error please provide us more details.

But I noticed that VisiCut can't be downloaded on Win11 with Edge because it gets blocked. Downloaded it with Firefox. I don't know if that is already an issue on Win10 and Edge because I am not using Windows.  Maybe something we should document for users?

**Comment by mgmax** [comment] 2022-01-15 09:22
Closing because the bug could not be reproduced and the original reporter did not respond.

**Closed by mgmax** 2022-01-15 09:22 UTC
