### ISSUE TITLE
"VisiCut is damaged and can’t be opened." Error in MacOS Sierra

### ISSUE THREAD

**Issue by agreiner29** [t-oster/VisiCut#393] opened 2016-11-30 18:26 UTC
The "allow applications from anywhere" is not available in MacOS Sierra. There is a workaround to enable it, but it is inconvenient.

**Comment by pelrun** [comment] 2016-12-01 08:17
We're aware of this issue, see #146.

**Comment by jsphpl** [comment] 2017-01-10 16:50
Check this answer for a workaround: http://apple.stackexchange.com/a/102358

**Comment by t-oster** [comment] 2017-01-10 20:36
i.e. try running `xattr -rc /Volumes/path/to/VisiCut.app` in your terminal

**Comment by t-oster** [comment] 2017-01-10 20:37
(closing this as duplicate of #146)

**Closed by t-oster** 2017-01-10 20:37 UTC
