### ISSUE TITLE
Linux patch

### ISSUE THREAD

**Issue by z4ziggy** [t-oster/VisiCut#351] opened 2016-03-27 01:06 UTC
the following is needed to have VisiCut look better on Linux:

```
diff --git a/src/com/t_oster/visicut/gui/MainView.java b/src/com/t_oster/visicut/gui/MainView.java
index 831f494..eee5b89 100644
--- a/src/com/t_oster/visicut/gui/MainView.java
+++ b/src/com/t_oster/visicut/gui/MainView.java
@@ -1896,7 +1896,7 @@ public class MainView extends javax.swing.JFrame
   {
     final FileFilter allFilter = VisicutModel.getInstance().getAllFileFilter();
     //On Mac os, awt.FileDialog looks more native
-    if (Helper.isMacOS())
+    if (Helper.isMacOS() || Helper.isLinux())
     {
       FileDialog openFileChooser = new FileDialog(this, bundle.getString("PLEASE SELECT A FILE"));
       openFileChooser.setMode(FileDialog.LOAD);

```

**Comment by mgmax** [comment] 2016-03-27 09:33
Can you please describe that in more detail, possibly with screenshots? 
It works for me without this change.

**Comment by z4ziggy** [comment] 2016-03-27 09:56
without the patch:

![nopatch](https://cloud.githubusercontent.com/assets/451833/14064850/26ea5fd4-f41b-11e5-9a5f-7f88648ed59c.png)

with the patch:

![patch](https://cloud.githubusercontent.com/assets/451833/14064852/326f8442-f41b-11e5-98e5-b92c0945895c.png)

**Comment by t-oster** [comment] 2016-03-27 10:02
Which distribution/window Manager/Toolkit/Java Version are you using? Some use the native file requester with FileDialog and some look better with JFileChooser. There is even a gtk specific implementation (lib/gtkfilechooser)

**Comment by mgmax** [comment] 2016-03-27 10:09
Okay, your request was not very clear. It is actually a duplicate of #317, so we should continue discussion there. It looks like your patch is the solution at least for Linux+Gnome.

**Comment by t-oster** [comment] 2016-03-27 11:08
yes, it is a duplicate of #317 so I close this. @z4ziggy please post your screenshots there together with exact distro/desktop environment/java-version. Maybe people with other constellations can test this too

**Closed by t-oster** 2016-03-27 11:08 UTC
