### ISSUE TITLE
GCODE - Bounding Box

### ISSUE THREAD

**Issue by thinkl33t** [t-oster/VisiCut#311] opened 2015-11-16 11:26 UTC
It would be handy to have the ability with gcode-based lasers to upload a gcode file that draws around the 'bounding box' of the current cuts you have loaded using G0 movements, to assist with aligning cuts to material on lasers without cameras.

**Comment by t-oster** [comment] 2015-12-16 09:03
duplicate of #181, please search for existing issues before submitting new ones.

**Closed by t-oster** 2015-12-16 09:03 UTC
