### ISSUE TITLE
exporting bounding boxes

### ISSUE THREAD

**Issue by LenoreHorner** [t-oster/VisiCut#487] opened 2018-12-03 23:35 UTC
When I use the Inkscape extension to send and svg image (made up of several copies of an original image) the drawing and the bounding boxes get exported with the same color to VisiCut (no matter whether I have each member selected or nothing selected).  This naturally makes the file not work out at all well.  Why are the bounding boxes being treated as lines that I drew?
![screen shot 2018-12-03 at 18 21 47](https://user-images.githubusercontent.com/23015014/49408410-25d1e580-f72a-11e8-84f4-e057a3c8beb9.png)
![screen shot 2018-12-03 at 18 22 05](https://user-images.githubusercontent.com/23015014/49408412-27031280-f72a-11e8-9baa-4529c09d8e86.png)

**Comment by LenoreHorner** [comment] 2018-12-03 23:39
Using group so that there is only one bounding box when selected in Inkscape changes nothing.  Do I have to hand-edit the original svg file so it doesn't have a bounding box?

**Comment by LenoreHorner** [comment] 2018-12-04 21:57
Thanks. Hadn't thought of checking using a web browser.  Looks fine there.  File is at https://www.dropbox.com/s/avqd5h6fhu03hel/Koch2-Compound.svg?dl=0.

**Comment by mgmax** [comment] 2018-12-05 19:20
Your file contains <svg:clipPath> elements which are currently unsupported. See also #15.
The bug is that Visicut should ignore them, but doesn't.

**Comment by LenoreHorner** [comment] 2018-12-05 22:02
Thank you!  That enables me to fix my files by hand as well as to take this up with the writers of the software that drew everything via clipPath elements.

**Comment by mgmax** [comment] 2019-11-01 13:09
Closing - duplicate of #15

**Closed by mgmax** 2019-11-01 13:09 UTC
